/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Lanzadera;
import javax.swing.JOptionPane;
import BasedeDatos.conexionBD;
import Clases.NoTripulado;
import Clases.Tripulado;
import Interfaces.Fabrica;

/**
 *
 * @author Emanuel
 */
public class AltaNave extends javax.swing.JFrame {
    private static AltaNave instance=null;
    
    public static AltaNave getInstance(){
        if(instance==null)
            instance=new AltaNave();
        return instance;
    }
    
    
    /**
     * Creates new form AltaNave
     */
    public AltaNave() {
        initComponents();
        txtProp.setVisible(false);
        txtOrb.setVisible(false);
        txtCantPasj.setVisible(false);
        lblProp.setVisible(false);
        lblOrb.setVisible(false);
        lblCantPasj.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtComb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo_tipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        txtProp = new javax.swing.JTextField();
        lblProp = new javax.swing.JLabel();
        txtOrb = new javax.swing.JTextField();
        lblOrb = new javax.swing.JLabel();
        lblCantPasj = new javax.swing.JLabel();
        txtCantPasj = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo");

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Peso:");

        jLabel4.setText("Combustible");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/navesita.png"))); // NOI18N

        combo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Lanzadera", "No Tripulada", "Tripulada" }));
        combo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        lblProp.setText("Propulsión:");

        lblOrb.setText("Orbita:");

        lblCantPasj.setText("Cant. Pasajeros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(lblProp)
                                    .addComponent(lblOrb)
                                    .addComponent(lblCantPasj))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOrb, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(combo_tipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtComb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                        .addComponent(txtProp))
                                    .addComponent(txtCantPasj, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtComb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProp)
                    .addComponent(txtProp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantPasj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantPasj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed
 public boolean verificarDatos(){
        if(txtCod.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un código", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtNom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de nave", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtPeso.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un peso", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtComb.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un combustible", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(combo_tipo.getSelectedItem().equals("Seleccione")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un Tipo de nave", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(combo_tipo.getSelectedItem().equals("Lanzadera")){
            if(txtProp.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar una propulsión", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }}
        else if(combo_tipo.getSelectedItem().equals("Tripulada")){
            if(txtOrb.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar una Orbita. EJ:1281299 km de la tierra", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
            if(txtCantPasj.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero de pasajeros", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }}
        else if(combo_tipo.getSelectedItem().equals("NoTripulada")){
            if(txtOrb.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar una orbita. EJ:1281299 km de la tierra", "ERROR", JOptionPane.ERROR_MESSAGE);
            return  false;
        }}
       
        return true;  
    
 }
 
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if(verificarDatos()){
        if(Fabrica.getInstancia().getInterfazNave().verificarNave(Integer.parseInt(txtCod.getText()))){
        javax.swing.JOptionPane.showMessageDialog(null, "Ya existe una nave con ese codigo!","ERROR!",0);
        }else{
        if(null != combo_tipo.getSelectedItem().toString()) // TODO add your handling code here:
        switch (combo_tipo.getSelectedItem().toString()) {
            case "Lanzadera":
                Lanzadera l = new Lanzadera();
                l.setActivo(1);
                l.setCodigo(Integer.parseInt(txtCod.getText()));
                l.setNombre(txtNom.getText());
                l.setPeso(Double.parseDouble(txtPeso.getText()));
                l.setCombustible(txtComb.getText());
                l.setEstado("En Base");
                l.setPropulsion(txtProp.getText());
                l.setTipo(combo_tipo.getSelectedItem().toString());
                conexionBD.getInstance().persist(l);
                JOptionPane.showMessageDialog(this, "Se ha creado la nave correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "No Tripulada":
                NoTripulado nt = new NoTripulado();
                nt.setActivo(1);
                nt.setCodigo(Integer.parseInt(txtCod.getText()));
                nt.setNombre(txtNom.getText());
                nt.setEstado("En Base");
                nt.setPeso(Double.parseDouble(txtPeso.getText()));
                nt.setCombustible(txtComb.getText());
                nt.setOrbita(txtOrb.getText());
                nt.setTipo(combo_tipo.getSelectedItem().toString());
                conexionBD.getInstance().persist(nt);
                JOptionPane.showMessageDialog(this, "Se ha creado la nave correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "Tripulada":
                Tripulado t = new Tripulado();
                t.setActivo(1);
                t.setCodigo(Integer.parseInt(txtCod.getText()));
                t.setNombre(txtNom.getText());
                t.setEstado("En Base");
                t.setPeso(Double.parseDouble(txtPeso.getText()));
                t.setCombustible(txtComb.getText());
                t.setOrbita(txtOrb.getText());
                t.setCant_pasajeros(Integer.parseInt(txtCantPasj.getText()));
                t.setTipo(combo_tipo.getSelectedItem().toString());
                conexionBD.getInstance().persist(t);
                JOptionPane.showMessageDialog(this, "Se ha creado la nave correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                break;
        }
          //Limpiar cajas de texto ---------------------------------------
            txtCod.setText("");
            txtNom.setText("");
            txtPeso.setText("");
            txtComb.setText(""); 
            txtOrb.setText("");
            txtProp.setText(""); 
            txtCantPasj.setText("");
        
    }
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void combo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoActionPerformed
        // TODO add your handling code here:
                if(null != combo_tipo.getSelectedItem().toString()) // TODO add your handling code here:
        switch (combo_tipo.getSelectedItem().toString()) {
            case "Lanzadera":
                 txtProp.setVisible(true);
                  lblProp.setVisible(true);
                  txtOrb.setVisible(false);
                  lblOrb.setVisible(false);
                  txtCantPasj.setVisible(false);
                  lblCantPasj.setVisible(false);
                   break;
            case "No Tripulada":
                  txtProp.setVisible(false);
                  lblProp.setVisible(false);
                  txtOrb.setVisible(true);
                  lblOrb.setVisible(true);
                  txtCantPasj.setVisible(false);
                  lblCantPasj.setVisible(false);
                break;
            case "Tripulada":
                  txtProp.setVisible(false);
                  lblProp.setVisible(false);
                  txtOrb.setVisible(true);
                  lblOrb.setVisible(true);
                  txtCantPasj.setVisible(true);
                  lblCantPasj.setVisible(true);
                 break;
            default:
                break;
        }
    }//GEN-LAST:event_combo_tipoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        AltaNave.instance=null;
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaNave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> combo_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCantPasj;
    private javax.swing.JLabel lblOrb;
    private javax.swing.JLabel lblProp;
    private javax.swing.JTextField txtCantPasj;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtComb;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtOrb;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtProp;
    // End of variables declaration//GEN-END:variables
}
