/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import BasedeDatos.conexionBD;
import Clases.Mision;
import Clases.Nave;
import Clases.PlanetaDestino;
import Interfaces.Fabrica;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel
 */
public final class AsignarMision extends javax.swing.JFrame {
private static AsignarMision instance=null;
private List<Nave> Nave=null;
private List<PlanetaDestino> Planeta=null;

    public static AsignarMision getInstance(){
        if(instance==null)
            instance=new AsignarMision();
        return instance;
    }
    /**
     * Creates new form AsignarMision
     */
    public AsignarMision() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarNaves();
        cargarPlanetas();
    }
public boolean verificarDatos(){
        if(txtCod.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un código", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtNom.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de misión", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtMision.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar una misión", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(txtDescrip.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar una descripción", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(cbo_Nave.getSelectedItem().equals("Seleccione")){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una nave", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(cbo_Planeta.getSelectedItem().equals("Seleccione")){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Planeta Destino. ", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
 
       
        return true;  
    
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbo_Nave = new javax.swing.JComboBox<>();
        lblProp1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescrip = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMision = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lblProp2 = new javax.swing.JLabel();
        cbo_Planeta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre:");

        cbo_Nave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cbo_Nave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_NaveActionPerformed(evt);
            }
        });

        lblProp1.setText("Nave:");

        txtDescrip.setColumns(20);
        txtDescrip.setRows(5);
        jScrollPane1.setViewportView(txtDescrip);

        jLabel4.setText("Descripción:");

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLabel3.setText("Misión");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        lblProp2.setText("Planeta Destino:");

        cbo_Planeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cbo_Planeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_PlanetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMision, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblProp2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbo_Planeta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblProp1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_Nave, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMision, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProp1)
                    .addComponent(cbo_Nave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProp2)
                    .addComponent(cbo_Planeta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_NaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_NaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_NaveActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if(verificarDatos()){
        if(Fabrica.getInstancia().getInterfazMision().verificarMision(Integer.parseInt(txtCod.getText()))){
        javax.swing.JOptionPane.showMessageDialog(null, "Ya existe una misión con ese codigo!","ERROR!",0);
        }else{
        Nave naveSel=null;
        for (Nave n : Nave) {
            if(n.getNombre().equals(cbo_Nave.getSelectedItem().toString())){
                naveSel=n;
                break;
            }
        }
        PlanetaDestino PSel=null;
        for (PlanetaDestino p : Planeta) {
            if(p.getNombre().equals(cbo_Planeta.getSelectedItem().toString())){
                PSel=p;
                break;
            }
        }
        Mision M = new Mision();
        M.setCodigo(Integer.parseInt(txtCod.getText()));
        M.setNombre(txtNom.getText());
        M.setMision(txtMision.getText());
        M.setEstado("En curso");
        M.setDescripcion(txtDescrip.getText());
        naveSel.setEstado("Misión en curso");
        M.setNave(naveSel);
        M.setPlanetadestino(PSel);
        conexionBD.getInstance().persist(M);
        
        JOptionPane.showMessageDialog(this, "Se ha creado la mision correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
        //Limpiar cajas de texto ---------------------------------------
        txtCod.setText("");
        txtNom.setText("");
        txtMision.setText("");
        txtDescrip.setText("");
    }//GEN-LAST:event_btn_guardarActionPerformed
    }
    }
    public void cargarNaves(){
        List<Nave> Naves=Fabrica.getInstancia().getInterfazNave().getAllNaves();
        Nave=Naves;
        Naves.forEach((Nave Nv)->{
            cbo_Nave.addItem(Nv.getNombre());        
        });
    }
        
    public void cargarPlanetas(){
        List<PlanetaDestino> Planetas=Fabrica.getInstancia().getInterfazPlaneta().getAllPlanetas();
        Planeta=Planetas;
        Planetas.forEach((PlanetaDestino Pl)->{
            cbo_Planeta.addItem(Pl.getNombre());        
        });
    }
    
    private void cbo_PlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_PlanetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_PlanetaActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
         AsignarMision.instance=null;
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarMision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarMision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarMision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarMision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarMision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> cbo_Nave;
    private javax.swing.JComboBox<String> cbo_Planeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProp1;
    private javax.swing.JLabel lblProp2;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextArea txtDescrip;
    private javax.swing.JTextField txtMision;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
