/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import BasedeDatos.conexionBD;
import Clases.Lanzadera;
import Clases.Mision;
import Clases.Nave;
import Clases.NoTripulado;
import Clases.Tripulado;
import java.util.List;
import javax.swing.JOptionPane;
import static org.hibernate.internal.util.collections.CollectionHelper.isEmpty;

/**
 *
 * @author Emanuel
 */
public class InfoNave extends javax.swing.JFrame {
    private static InfoNave instance=null;
    
    public static InfoNave getInstance(Nave n){
        if(instance==null)
            instance=new InfoNave(n);
        return instance;
    }
    private final Nave n;
    /**
     * Creates new form InfoLanzadera
     */
    public InfoNave(Nave n) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.n = n;
        txtCod.setText(String.valueOf(n.getCodigo()));
        txtNom.setText(n.getNombre());
        txtPeso.setText(String.valueOf(n.getPeso()));
        txtComb.setText(n.getCombustible());
        combo_tipo.setSelectedItem(n.getTipo());
        txtEstado.setText(n.getEstado());
        
        if(n instanceof Lanzadera){
            Lanzadera l = (Lanzadera) n;
            txtProp.setText(l.getPropulsion());
            txtProp.setVisible(true);
            lblProp.setVisible(true);
        }else if(n instanceof Tripulado){
            Tripulado t = (Tripulado) n;
           txtOrb.setText(t.getOrbita());
           txtCantPasj.setText(String.valueOf(t.getCant_pasajeros()));
           txtCantPasj.setVisible(true);
           lblCantPasj.setVisible(true);
           txtOrb.setVisible(true);
           lblOrb.setVisible(true);
        }else if(n instanceof NoTripulado){
            NoTripulado nt = (NoTripulado) n;
           txtOrb.setText(nt.getOrbita());
                  txtOrb.setVisible(true);
                  lblOrb.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        combo_tipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        txtCod = new javax.swing.JTextField();
        btn_elim = new javax.swing.JButton();
        txtNom = new javax.swing.JTextField();
        txtProp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblProp = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtOrb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblOrb = new javax.swing.JLabel();
        txtComb = new javax.swing.JTextField();
        lblCantPasj = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantPasj = new javax.swing.JTextField();
        btn_guardar1 = new javax.swing.JButton();
        txtEstado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/navesita.png"))); // NOI18N

        combo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Lanzadera", "No Tripulada", "Tripulada" }));
        combo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo");

        jLabel1.setText("Codigo");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        btn_elim.setText("Eliminar");
        btn_elim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elimActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        lblProp.setText("Propulsión:");

        jLabel3.setText("Peso:");

        lblOrb.setText("Orbita:");

        lblCantPasj.setText("Cant. Pasajeros");

        jLabel4.setText("Combustible");

        btn_guardar1.setText("Guardar");
        btn_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar1ActionPerformed(evt);
            }
        });

        txtEstado.setEditable(false);

        jLabel7.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(lblProp)
                                            .addComponent(lblOrb))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCantPasj)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantPasj, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(combo_tipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtComb, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtProp, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtOrb, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 3, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtComb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProp)
                    .addComponent(txtProp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrb)
                    .addComponent(txtOrb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantPasj)
                    .addComponent(txtCantPasj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoActionPerformed
        // TODO add your handling code here:
        if(null != combo_tipo.getSelectedItem().toString()) // TODO add your handling code here:
        switch (combo_tipo.getSelectedItem().toString()) {
            case "Lanzadera":
            txtProp.setVisible(true);
            lblProp.setVisible(true);
            txtOrb.setVisible(false);
            lblOrb.setVisible(false);
            txtCantPasj.setVisible(false);
            lblCantPasj.setVisible(false);
            break;
            case "No Tripulada":
            txtProp.setVisible(false);
            lblProp.setVisible(false);
            txtOrb.setVisible(true);
            lblOrb.setVisible(true);
            txtCantPasj.setVisible(false);
            lblCantPasj.setVisible(false);
            break;
            case "Tripulada":
            txtProp.setVisible(false);
            lblProp.setVisible(false);
            txtOrb.setVisible(true);
            lblOrb.setVisible(true);
            txtCantPasj.setVisible(true);
            lblCantPasj.setVisible(true);
            break;
            default:
            break;
        }
    }//GEN-LAST:event_combo_tipoActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void btn_elimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elimActionPerformed
        int cont=0;
        List <Mision> misiones = n.getMisiones();
        if (isEmpty(misiones)){
        conexionBD.getInstance().delete(n);
        JOptionPane.showMessageDialog(this, "Se ha borrado la nave correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
        //Limpiar cajas de texto ---------------------------------------
        txtCod.setText("");
        txtNom.setText("");
        txtPeso.setText("");
        txtComb.setText("");
        txtOrb.setText("");
        txtProp.setText("");
        txtCantPasj.setText("");
        }else{
        for (Mision m : misiones) {
            if(m.getEstado().equals("En curso")){
               cont++;
               }
        }
        if(cont>0){
            JOptionPane.showMessageDialog(this, "Primero debe eliminar o finalizar las misiones asignadas a esta nave", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            n.setActivo(0);
            conexionBD.getInstance().merge(n);
            JOptionPane.showMessageDialog(this, "Se ha dado de baja la nave correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
        }

        
    }

    }//GEN-LAST:event_btn_elimActionPerformed

    private void btn_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar1ActionPerformed
        // TODO add your handling code here:
        if (n.getCodigo() == Integer.parseInt(txtCod.getText())){
            if(null != combo_tipo.getSelectedItem().toString()) // TODO add your handling code here:
        switch (combo_tipo.getSelectedItem().toString()) {
            case "Lanzadera":
                Lanzadera l = new Lanzadera();
                l.setActivo(1);
                l.setCodigo(Integer.parseInt(txtCod.getText()));
                l.setNombre(txtNom.getText());
                l.setPeso(Double.parseDouble(txtPeso.getText()));
                l.setCombustible(txtComb.getText());
                l.setEstado("En Base");
                l.setPropulsion(txtProp.getText());
                l.setTipo(combo_tipo.getSelectedItem().toString());
                conexionBD.getInstance().merge(l);
                JOptionPane.showMessageDialog(this, "Se ha actualizado la nave correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "No Tripulada":
                NoTripulado nt = new NoTripulado();
                nt.setActivo(1);
                nt.setCodigo(Integer.parseInt(txtCod.getText()));
                nt.setNombre(txtNom.getText());
                nt.setEstado("En Base");
                nt.setPeso(Double.parseDouble(txtPeso.getText()));
                nt.setCombustible(txtComb.getText());
                nt.setOrbita(txtOrb.getText());
                nt.setTipo(combo_tipo.getSelectedItem().toString());
                conexionBD.getInstance().merge(nt);
                JOptionPane.showMessageDialog(this, "Se ha actualizado la nave correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                break;
            case "Tripulada":
                Tripulado t = new Tripulado();
                t.setActivo(1);
                t.setCodigo(Integer.parseInt(txtCod.getText()));
                t.setNombre(txtNom.getText());
                t.setEstado("En Base");
                t.setPeso(Double.parseDouble(txtPeso.getText()));
                t.setCombustible(txtComb.getText());
                t.setOrbita(txtOrb.getText());
                t.setCant_pasajeros(Integer.parseInt(txtCantPasj.getText()));
                t.setTipo(combo_tipo.getSelectedItem().toString());
                conexionBD.getInstance().merge(t);
                JOptionPane.showMessageDialog(this, "Se ha actualizado la nave correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                break;
        }
          //Limpiar cajas de texto ---------------------------------------
            txtCod.setText("");
            txtNom.setText("");
            txtPeso.setText("");
            txtComb.setText(""); 
            txtOrb.setText("");
            txtProp.setText(""); 
            txtCantPasj.setText("");
        
    }
        
    }//GEN-LAST:event_btn_guardar1ActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        ListaNaves ln = new ListaNaves();
        ln.verNaves();
        InfoNave.instance=null;
        this.dispose();

    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoNave(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_elim;
    private javax.swing.JButton btn_guardar1;
    private javax.swing.JComboBox<String> combo_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCantPasj;
    private javax.swing.JLabel lblOrb;
    private javax.swing.JLabel lblProp;
    private javax.swing.JTextField txtCantPasj;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtComb;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtOrb;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtProp;
    // End of variables declaration//GEN-END:variables
}
