/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import BasedeDatos.conexionBD;
import Clases.Mision;
import Clases.Nave;
import Clases.PlanetaDestino;
import Interfaces.Fabrica;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static org.hibernate.internal.util.collections.CollectionHelper.isEmpty;

/**
 *
 * @author Emanuel
 */
public class ListaPlanetas extends javax.swing.JFrame {
    private static ListaPlanetas instance=null;
    PlanetaDestino pd = new PlanetaDestino();
    private List<PlanetaDestino> planetas=null;
    
        public static ListaPlanetas getInstance(){
        if(instance==null)
            instance=new ListaPlanetas();
        return instance;
    }
    /**
     * Creates new form ListaPlanetas
     */
    public ListaPlanetas() {
        initComponents();
        verPlanetas();
    }

            public final void verPlanetas() {
        DefaultTableModel modelo = (DefaultTableModel) jTablePlanetas.getModel();
        modelo.setRowCount(0);
        planetas = Fabrica.getInstancia().getInterfazPlaneta().getAllPlanetas();
        for (int i = 0; i < planetas.size(); i++) {
            PlanetaDestino p=(PlanetaDestino)planetas.get(i);
            Object[] dat = {p.getCodigo(),p.getDescripcion(),p.getNombre(),p.getTamaño()};
            modelo.addRow(dat);
        }
        DefaultTableCellRenderer Alinear = new DefaultTableCellRenderer();
        Alinear.setHorizontalAlignment(SwingConstants.CENTER);//.LEFT .RIGHT .CENTER
        jTablePlanetas.getColumnModel().getColumn(0).setCellRenderer(Alinear);
        jTablePlanetas.getColumnModel().getColumn(1).setCellRenderer(Alinear);
        jTablePlanetas.getColumnModel().getColumn(2).setCellRenderer(Alinear);
        jTablePlanetas.getColumnModel().getColumn(3).setCellRenderer(Alinear);


    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlanetas = new javax.swing.JTable();
        btn_cancelar = new javax.swing.JButton();
        btn_elim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePlanetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Nombre", "Tamaño"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePlanetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePlanetasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePlanetas);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_elim.setText("Eliminar");
        btn_elim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
      ListaPlanetas.instance=null;
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void jTablePlanetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePlanetasMouseClicked
        // TODO add your handling code here:
       pd  =  Fabrica.getInstancia().getInterfazPlaneta().getPlaneta((Integer)jTablePlanetas.getValueAt(jTablePlanetas.getSelectedRow(), 0));
    }//GEN-LAST:event_jTablePlanetasMouseClicked

    private void btn_elimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elimActionPerformed
        // TODO add your handling code here:
        int cont=0;
        List <Mision> misiones = pd.getMisiones();
        if (isEmpty(misiones)){
        conexionBD.getInstance().delete(pd);
        JOptionPane.showMessageDialog(this, "Se ha borrado el planeta correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
        }else{
        for (Mision m : misiones) {
            if(m.getEstado().equals("En curso")){
               cont++;
               }
        }
        if(cont>0){
            JOptionPane.showMessageDialog(this, "Primero debe eliminar o finalizar las misiones asignadas a esta nave", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            pd.setActivo(0);
            conexionBD.getInstance().merge(pd);
            JOptionPane.showMessageDialog(this, "Se ha dado de baja el planeta correctamente", "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
        }
    
    }
        verPlanetas();
    }//GEN-LAST:event_btn_elimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPlanetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_elim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlanetas;
    // End of variables declaration//GEN-END:variables
}
